#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
group: edge


################
# build matrix #
################

jobs:
  include:

  - os: linux
    compiler: gcc
    env:
      - COMPILER_CC=/usr/bin/gcc-4.9
      - COMPILER_CXX=/usr/bin/g++-4.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9', 'gcc-4.9']


  # OSX / Clang

  - os: osx
    osx_image: xcode9.3
    env:
      - COMPILER_CC=gcc
      - COMPILER_CXX=g++

  - os: osx
    osx_image: xcode9.4
    env:
      - COMPILER_CC=gcc
      - COMPILER_CXX=g++

  - os: osx
    osx_image: xcode10
    env:
      - COMPILER_CC=gcc
      - COMPILER_CXX=g++

  - os: osx
    osx_image: xcode10.1
    env:
      - COMPILER_CC=gcc
      - COMPILER_CXX=g++

  - os: osx
    osx_image: xcode10.2
    env:
      - COMPILER_CC=gcc
      - COMPILER_CXX=g++

  - os: osx
    osx_image: xcode11.2
    env:
      - COMPILER_CC=gcc
      - COMPILER_CXX=g++

  # Linux / GCC

  - os: linux
    compiler: gcc
    env:
      - COMPILER_CC=gcc-4.8
      - COMPILER_CXX=g++-4.8
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.8', 'gcc-4.8']

  - os: linux
    compiler: gcc
    env:
      - COMPILER_CC=gcc-4.9
      - COMPILER_CXX=g++-4.9
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9', 'gcc-4.9']

  - os: linux
    compiler: gcc
    env:
      - COMPILER_CC=gcc-5
      - COMPILER_CXX=g++-5
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5', 'gcc-5']

  - os: linux
    compiler: gcc
    env:
      - COMPILER_CC=gcc-6
      - COMPILER_CXX=g++-6
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-6', 'gcc-6']

  - os: linux
    compiler: gcc
    env:
      - COMPILER_CC=gcc-7
      - COMPILER_CXX=g++-7
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-7', 'gcc-7']

  - os: linux
    compiler: gcc
    env:
      - COMPILER_CC=gcc-8
      - COMPILER_CXX=g++-8
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8', 'gcc-8']

  - os: linux
    compiler: gcc
    env:
      - COMPILER_CC=gcc-9
      - COMPILER_CXX=g++-9
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-9', 'gcc-9']

  - os: linux
    compiler: gcc
    env:
      - COMPILER_CC=gcc-9
      - COMPILER_CXX=g++-9
      - CXXFLAGS=-std=c++2a
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-9', 'gcc-9']

  # Linux / Clang

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-3.5
      - COMPILER_CXX=clang++-3.5
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
        packages: ['g++-6', 'clang-3.5']

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-3.6
      - COMPILER_CXX=clang++-3.6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
        packages: ['g++-6', 'clang-3.6']

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-3.7
      - COMPILER_CXX=clang++-3.7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
        packages: ['g++-6', 'clang-3.7']

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-3.8
      - COMPILER_CXX=clang++-3.8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-6', 'clang-3.8']

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-3.9
      - COMPILER_CXX=clang++-3.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-6', 'clang-3.9']

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-4.0
      - COMPILER_CXX=clang++-4.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
        packages: ['g++-6', 'clang-4.0']

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-5.0
      - COMPILER_CXX=clang++-5.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
        packages: ['g++-6', 'clang-5.0']

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-6.0
      - COMPILER_CXX=clang++-6.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['g++-6', 'clang-6.0']

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-7
      - COMPILER_CXX=clang++-7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
        packages: ['g++-6', 'clang-7']

  - os: linux
    compiler: clang
    env:
      - COMPILER_CC=clang-7
      - COMPILER_CXX=clang++-7
      - CXXFLAGS=-std=c++1z
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
        packages: ['g++-6', 'clang-7']


################
# build script #
################

script:
  # compile and execute unit tests
  - make CC=${COMPILER_CC} && make run
