#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
group: edge


################
# build matrix #
################

jobs:
  include:

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-4.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9']


  # OSX / Clang

  - os: osx
    osx_image: xcode9.3

  - os: osx
    osx_image: xcode9.4

  - os: osx
    osx_image: xcode10

  - os: osx
    osx_image: xcode10.1

  - os: osx
    osx_image: xcode10.2

  - os: osx
    osx_image: xcode11.2

  # Linux / GCC

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-4.8
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.8']

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-4.9
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9']

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-5
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5']

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-6
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-6']

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-7
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-7']

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-8
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8']

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-9
      - CXXFLAGS=-std=c++11
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-9']

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-9
      - CXXFLAGS=-std=c++2a
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-9']

  # Linux / Clang

  - os: linux
    compiler: clang
    env: COMPILER=clang++-3.5
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
        packages: ['g++-6', 'clang-3.5']

  - os: linux
    compiler: clang
    env: COMPILER=clang++-3.6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
        packages: ['g++-6', 'clang-3.6']

  - os: linux
    compiler: clang
    env: COMPILER=clang++-3.7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
        packages: ['g++-6', 'clang-3.7']

  - os: linux
    compiler: clang
    env: COMPILER=clang++-3.8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-6', 'clang-3.8']

  - os: linux
    compiler: clang
    env: COMPILER=clang++-3.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-6', 'clang-3.9']

  - os: linux
    compiler: clang
    env: COMPILER=clang++-4.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
        packages: ['g++-6', 'clang-4.0']

  - os: linux
    compiler: clang
    env: COMPILER=clang++-5.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
        packages: ['g++-6', 'clang-5.0']

  - os: linux
    compiler: clang
    env: COMPILER=clang++-6.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['g++-6', 'clang-6.0']

  - os: linux
    compiler: clang
    env: COMPILER=clang++-7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
        packages: ['g++-6', 'clang-7']

  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-7
      - CXXFLAGS=-std=c++1z
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
        packages: ['g++-6', 'clang-7']


################
# build script #
################

script:
  # compile and execute unit tests
  - make && make run
