name: macOS

on: [push]
env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: single_include Configure CMake C
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DNN_LANG=OFF -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: single_include Build C
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel 10

    - name: single_include Test C
      working-directory: ${{runner.workspace}}/build
      run: ctest


    - name: single_include Configure CMake CPP
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DNN_LANG=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: single_include Build CPP
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel 10

    - name: single_include Test CPP
      working-directory: ${{runner.workspace}}/build
      run: ctest


    # Multiple headers
    - name: Configure CMake C
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DNN_LANG=OFF -DNN_MultipleHeaders=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build C
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel 10

    - name: Test C
      working-directory: ${{runner.workspace}}/build
      run: ctest

    - name: Configure CMake CPP
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DNN_LANG=ON -DNN_MultipleHeaders=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build CPP
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel 10

    - name: Test CPP
      working-directory: ${{runner.workspace}}/build
      run: ctest
