name: Ubuntu

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake C
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build C
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --parallel 10
    
    - name: Test C
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make run

    
    - name: Configure CMake CPP
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DLANG=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    
    - name: Build CPP
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --parallel 10

    - name: Test CPP
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make run
